### ISSUE TITLE
Works only on edit mode

### ISSUE THREAD

**Issue by KINGSABRI** [keith0305/inkdrop-plugin-scroll-to-top#1]
Hi 
Thank you for making this plugin available. I've requested this to be a built-in function for a long time.

The plugin works well in edit (and side by side) mode but not on the preview mode

Thanks

**Comment by keith0305** [comment]
Hey thanks. Yeah I wanted this feature myself so I made it.
And you are right I did not make the functionality to be available in the preview mode.
Thanks for the idea I will implement it in the next update.

**Comment by keith0305** [comment]
Release v0.3.0 has fixed this.

**Comment by KINGSABRI** [comment]
Tested now, and it works like a charm!

Thank you!
